# Generated by Django 5.0.2 on 2024-04-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=25, verbose_name='Сезон')),
                ('start_date', models.DateTimeField(verbose_name='Дата старта')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('season_slug', models.SlugField(max_length=255, unique=True)),
                ('name_winner', models.CharField(default='Unknown', editable=False, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name_team', models.CharField(default='Unknown', max_length=25, verbose_name='Название команды')),
                ('short_name', models.CharField(max_length=10, verbose_name='Сокращённое название')),
                ('tla', models.CharField(max_length=10, verbose_name='Аббревиатура')),
                ('logo', models.ImageField(blank=True, default='default_logo.png', null=True, upload_to='team_logos/', verbose_name='Лого')),
                ('team_slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_team', models.CharField(default='Unknown', editable=False, max_length=25)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('played_games', models.PositiveIntegerField(blank=True, null=True)),
                ('won', models.PositiveIntegerField(blank=True, null=True)),
                ('draw', models.PositiveIntegerField(blank=True, null=True)),
                ('lost', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
                ('goals_for', models.PositiveIntegerField(blank=True, null=True)),
                ('goals_against', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_different', models.IntegerField(blank=True, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='match.seasons')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team', to='match.team')),
            ],
        ),
        migrations.AddField(
            model_name='seasons',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='match.team'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(default='Unknown', editable=False, max_length=25)),
                ('name_team', models.CharField(default='Unknown', editable=False, max_length=25)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('nationality', models.CharField(default='Unknown', max_length=40, verbose_name='Национальность')),
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.CharField(default='Unknown', editable=False, max_length=25, verbose_name='Позиция')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='match.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Дата и время матча')),
                ('home_team_name', models.CharField(default='Unknown', editable=False, max_length=25)),
                ('away_team_name', models.CharField(default='Unknown', editable=False, max_length=25)),
                ('score_home', models.PositiveIntegerField(blank=True, null=True)),
                ('score_away', models.PositiveIntegerField(blank=True, null=True)),
                ('logo_home', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('logo_away', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('status', models.CharField(default='Unknown', max_length=30, verbose_name='Статус')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='match.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='match.team')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('name', models.CharField(default='Unknown', editable=False, max_length=25)),
                ('name_team', models.CharField(default='Unknown', editable=False, max_length=25)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('nationality', models.CharField(default='Unknown', max_length=40, verbose_name='Национальность')),
                ('coach_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contract_start', models.IntegerField(blank=True, null=True, verbose_name='Начало контракта')),
                ('contract_end', models.IntegerField(blank=True, null=True, verbose_name='Окончание контракта')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coaches', to='match.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
